
export const SESSION_KEYS = {
    TOKEN: 'TOKEN',
    FIRSTNAME: 'FIRSTNAME',
    LASTNAME: 'LASTNAME',
    PHONE: 'PHONE',
    EMAIL: 'EMAIL',
    KEY: 'KEY',
    LASTMESSAGE: 'LASTMESSAGE',
    CONTEXT: 'CONTEXT',
    SENTIMENT: 'SENTIMENT',
    SESSION_ID: 'SESSION_ID',
    QUESTION: 'QUESTION',
    LASTREQUEST: 'LASTREQUEST',
    PREVIOUS_STATUS: 'PREVIOUS_STATUS',
    AWAITING_EMAIL: 'AWAITING_EMAIL',
    AWAITING_NAME: 'AWAITING_NAME',
    IP_ADDRESS: 'IP_ADDRESS',
    SERVICE: 'SERVICE'

};


export const CONTEXT_KEYS = {
  CONTEXT_INFO: 'context_info'
};

export const SCHEDULE_KEYS = {
  SCHEDULE_INFO: 'schedule_info'
};